package gui;

import java.awt.event.KeyEvent;
import java.util.ArrayList;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.Border;

import services.BuildServices;

public class TelaInicio extends JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form TelaInicio
	 */
	public TelaInicio() {
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		btGDelta = new javax.swing.ButtonGroup();
		panelPrincipal = new javax.swing.JPanel();
		cbAgents = new javax.swing.JCheckBox();
		cbEJB = new javax.swing.JCheckBox();
		cbBPM = new javax.swing.JCheckBox();
		cbGUI = new javax.swing.JCheckBox();
		cbMod = new javax.swing.JCheckBox();
		cbWS = new javax.swing.JCheckBox();
		cbDelta = new javax.swing.JCheckBox();
		rbOne = new javax.swing.JRadioButton();
		labelWhatDelta = new javax.swing.JLabel();
		rbMais = new javax.swing.JRadioButton();
		tfDeltaInicio = new javax.swing.JTextField();
		tfDeltaFinal = new javax.swing.JTextField();
		labelDeltaInicio = new javax.swing.JLabel();
		labelDeltaFinal = new javax.swing.JLabel();
		taOutPut = new javax.swing.JTextArea();
		labelTitle = new javax.swing.JLabel();
		btInstalar = new javax.swing.JButton();
		panelServer = new javax.swing.JPanel();
		cbServer = new javax.swing.JComboBox();
		panelDelta = new JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Wellcome to application - OM Deploy helper");
		setMinimumSize(new java.awt.Dimension(700, 700));
		setPreferredSize(new java.awt.Dimension(700, 700));
		getContentPane().setLayout(null);

		panelPrincipal.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Informações do pacote"));
		panelPrincipal.setToolTipText("Insira informações do pacote");
		panelPrincipal.setLayout(null);

		cbAgents.setText("Agents");
		cbAgents.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				cbAgentsStateChanged(evt);
			}
		});
		panelPrincipal.add(cbAgents);
		cbAgents.setBounds(20, 30, 59, 23);

		cbEJB.setText("EJBs");
		cbEJB.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				cbEJBStateChanged(evt);
			}
		});
		panelPrincipal.add(cbEJB);
		cbEJB.setBounds(320, 30, 47, 23);

		cbBPM.setText("BPMs");
		cbBPM.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				cbBPMStateChanged(evt);
			}
		});
		panelPrincipal.add(cbBPM);
		cbBPM.setBounds(420, 30, 51, 23);

		cbGUI.setText("GUI");
		cbGUI.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				cbGUIStateChanged(evt);
			}
		});
		panelPrincipal.add(cbGUI);
		cbGUI.setBounds(120, 30, 43, 23);

		cbMod.setText("Modules");
		cbMod.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				cbModStateChanged(evt);
			}
		});
		panelPrincipal.add(cbMod);
		cbMod.setBounds(220, 30, 81, 23);

		cbWS.setText("WS");
		cbWS.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				cbWSStateChanged(evt);
			}
		});
		panelPrincipal.add(cbWS);
		cbWS.setBounds(520, 30, 41, 23);

		cbDelta.setText("SQL-Delta");
		cbDelta.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				cbDeltaStateChanged(evt);
			}
		});
		panelPrincipal.add(cbDelta);
		cbDelta.setBounds(20, 70, 73, 23);

		btGDelta.add(rbOne);
		rbOne.setText("1");
		rbOne.setEnabled(false);
		rbOne.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				rbOneStateChanged(evt);
			}
		});
		panelPrincipal.add(rbOne);
		rbOne.setBounds(20, 140, 40, 23);

		labelWhatDelta.setText("Quantos deltas?");
		panelPrincipal.add(labelWhatDelta);
		labelWhatDelta.setBounds(20, 120, 90, 14);

		btGDelta.add(rbMais);
		rbMais.setText("Mais de 1");
		rbMais.setEnabled(false);
		rbMais.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				rbMaisStateChanged(evt);
			}
		});
		panelPrincipal.add(rbMais);
		rbMais.setBounds(70, 140, 80, 23);

		tfDeltaInicio.setEnabled(false);
		panelPrincipal.add(tfDeltaInicio);
		tfDeltaInicio.setBounds(160, 140, 50, 20);
		tfDeltaInicio.addKeyListener(new java.awt.event.KeyListener() {

			public void keyTyped(KeyEvent e) {
				tfDeltaKeyTyped(e);

			}

			public void keyPressed(KeyEvent e) {

			}

			public void keyReleased(KeyEvent e) {
				// TODO Auto-generated method stub

			}

		});

		tfDeltaFinal.setEnabled(false);
		panelPrincipal.add(tfDeltaFinal);
		tfDeltaFinal.setBounds(250, 140, 50, 20);
		tfDeltaFinal.addKeyListener(new java.awt.event.KeyListener() {

			public void keyTyped(KeyEvent e) {
				tfDeltaKeyTyped(e);

			}

			public void keyPressed(KeyEvent e) {
				// TODO Auto-generated method stub

			}

			public void keyReleased(KeyEvent e) {
				// TODO Auto-generated method stub

			}

		});

		labelDeltaInicio.setText("Delta (início)");
		panelPrincipal.add(labelDeltaInicio);
		labelDeltaInicio.setBounds(160, 120, 70, 14);

		labelDeltaFinal.setText("Delta (final)");
		panelPrincipal.add(labelDeltaFinal);
		labelDeltaFinal.setBounds(250, 120, 60, 14);

		getContentPane().add(panelPrincipal);
		panelPrincipal.setBounds(40, 90, 610, 180);

		labelTitle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		labelTitle.setText("Defina os dados da instalação");
		getContentPane().add(labelTitle);
		labelTitle.setBounds(40, 0, 250, 40);

		btInstalar.setText("Instalar");
		btInstalar.setEnabled(false);
		btInstalar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btInstalarActionPerformed(evt);
			}
		});
		getContentPane().add(btInstalar);
		btInstalar.setBounds(40, 280, 80, 30);
		getContentPane().add(taOutPut);
		taOutPut.setBounds(40, 350, 600, 250);
		taOutPut.setEditable(false);
		taOutPut.setVisible(true);

		panelServer
				.setBorder(javax.swing.BorderFactory
						.createTitledBorder("Escolha o servidor onde a instalação será realizada"));
		panelServer.setLayout(null);

		cbServer.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"10.1.43.87", "10.1.43.110" }));
		panelServer.add(cbServer);
		cbServer.setBounds(20, 20, 110, 22);

		getContentPane().add(panelServer);
		panelServer.setBounds(40, 40, 610, 50);

		pack();
	}// </editor-fold>

	private void cbDeltaStateChanged(javax.swing.event.ChangeEvent evt) {
		if (cbDelta.isSelected()) {
			rbOne.setEnabled(true);
			rbMais.setEnabled(true);
		} else {
			rbOne.setEnabled(false);
			rbMais.setEnabled(false);
			tfDeltaInicio.setEnabled(false);
			tfDeltaFinal.setEnabled(false);
		}
		isSomeItemSelected();
	}

	private void rbOneStateChanged(javax.swing.event.ChangeEvent evt) {
		if (rbOne.isSelected()) {
			tfDeltaInicio.setEnabled(true);
			tfDeltaFinal.setEnabled(false);
		}
	}

	private void rbMaisStateChanged(javax.swing.event.ChangeEvent evt) {
		if (rbMais.isSelected()) {
			tfDeltaInicio.setEnabled(true);
			tfDeltaFinal.setEnabled(true);
		}
	}

	private void cbAgentsStateChanged(javax.swing.event.ChangeEvent evt) {
		isSomeItemSelected();
	}

	private void cbGUIStateChanged(javax.swing.event.ChangeEvent evt) {
		isSomeItemSelected();
	}

	private void cbModStateChanged(javax.swing.event.ChangeEvent evt) {
		isSomeItemSelected();
	}

	private void cbEJBStateChanged(javax.swing.event.ChangeEvent evt) {
		isSomeItemSelected();
	}

	private void cbBPMStateChanged(javax.swing.event.ChangeEvent evt) {
		isSomeItemSelected();
	}

	private void cbWSStateChanged(javax.swing.event.ChangeEvent evt) {
		isSomeItemSelected();
	}

	private void tfDeltaKeyTyped(java.awt.event.KeyEvent evt) {
		String caracteres = "0987654321";
		if (!caracteres.contains(evt.getKeyChar() + "")) {
			evt.consume();
		}
	}

	private void btInstalarActionPerformed(java.awt.event.ActionEvent evt){
		String server = cbServer.getSelectedItem().toString();
		BuildServices build = new BuildServices(server,
				isSomeJavaItemSelected());
		build.executeBuildAndDeployScripts(getpkgsToInstall());

	}
	

	private ArrayList<String> getpkgsToInstall() {
		ArrayList<String> pkgs = new ArrayList<String>();
		if (cbEJB.isSelected()) {
			pkgs.add("EJB");
		}
		if (cbMod.isSelected()) {
			pkgs.add("MOD");
		}
		if (cbGUI.isSelected()) {
			pkgs.add("GUI");
		}
		if (cbWS.isSelected()) {
			pkgs.add("WS");
		}
		if (cbBPM.isSelected()) {
			pkgs.add("BPM");
		}
		if (cbAgents.isSelected()) {
			pkgs.add("AGE");
		}
		if (cbMod.isSelected()) {
			pkgs.add("MOD");
		}
		if (cbDelta.isSelected()) {
			if (rbOne.isSelected()) {
				pkgs.add("Delta-" + tfDeltaInicio.getText());
			} else {
				int deltaInicio = Integer.parseInt(tfDeltaInicio.getText());
				int deltaFinal = Integer.parseInt(tfDeltaFinal.getText());
				for (int i = deltaInicio; i <= deltaFinal; i++) {
					pkgs.add("Delta-" + String.valueOf(i));
				}
			}
		}

		return pkgs;
	}

	private boolean isSomeJavaItemSelected() {
		return (cbAgents.isSelected() || cbEJB.isSelected()
				|| cbGUI.isSelected() || cbMod.isSelected()
				|| cbWS.isSelected() || cbBPM.isSelected());
	}

	private void isSomeItemSelected() {
		if (isSomeJavaItemSelected() || cbDelta.isSelected()) {
			btInstalar.setEnabled(true);
		} else {
			btInstalar.setEnabled(false);
		}

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaInicio().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.ButtonGroup btGDelta;
	private javax.swing.JButton btInstalar;
	private javax.swing.JCheckBox cbAgents;
	private javax.swing.JCheckBox cbBPM;
	private javax.swing.JCheckBox cbDelta;
	private javax.swing.JCheckBox cbEJB;
	private javax.swing.JCheckBox cbGUI;
	private javax.swing.JCheckBox cbMod;
	private javax.swing.JComboBox cbServer;
	private javax.swing.JCheckBox cbWS;
	private javax.swing.JLabel labelDeltaFinal;
	private javax.swing.JLabel labelDeltaInicio;
	private javax.swing.JLabel labelTitle;
	private javax.swing.JLabel labelWhatDelta;
	private javax.swing.JPanel panelPrincipal;
	private javax.swing.JPanel panelServer;
	private javax.swing.JPanel panelDelta;
	private javax.swing.JTextArea taOutPut;
	private javax.swing.JRadioButton rbMais;
	private javax.swing.JRadioButton rbOne;
	private javax.swing.JTextField tfDeltaFinal;
	private javax.swing.JTextField tfDeltaInicio;
	// End of variables declaration
}